version: "3.8"

services:
  api:
    build: .
    container_name: api-customer
    restart: always
    ports:
      - "21401:21401"
    depends_on:
      - mongo-customer
      - rabbitmq-customer
    environment:
      NODE_ENV: production
      MONGO_URI: "mongodb://mongo-customer:27017/customers"
      RABBITMQ_URL: "amqp://rabbitmq-customer"
    networks:
      - app_network

  mongo-customer:
    image: mongo:5
    container_name: mongo-customer
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app_network

  rabbitmq-customer:
    image: rabbitmq:management
    container_name: rabbitmq-customer
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

  prometheus-customer:
    image: prom/prometheus
    container_name: prometheus-customer
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app_network

  grafana-customer:
    image: grafana/grafana
    container_name: grafana-customer
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
